# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Facebook' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Facebook
  pod 'Auth0', '~> 1.0'
  pod 'FacebookCore', '~> 0.9'
  pod 'FacebookLogin', '~> 0.9'

end
