# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'signinwithapple' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for signinwithapple
  pod 'Auth0', :git => 'https://github.com/auth0/Auth0.swift.git', :branch => 'added-apple-token-exchange'
  
end
